# Generated by Django 5.1.7 on 2025-04-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_foodlisting_image_foodlisting_images'),
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.foodlisting'),
        ),
    ]
