# Generated by Django 5.1.7 on 2025-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_otpstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='uploaded_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
