# Generated by Django 5.1.7 on 2025-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_vendor_uploaded_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
