# Generated by Django 5.1.7 on 2025-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_foodlisting_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
