# Generated by Django 5.1.7 on 2025-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_foodlisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlisting',
            name='image',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image paths/URLs'),
        ),
    ]
