# Generated by Django 5.1.7 on 2025-04-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_foodlisting_image_foodlisting_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
