# Generated by Django 5.2 on 2025-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_promotion_vendorcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcategory',
            name='vendor',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, help_text='Current latitude of delivery agent', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, help_text='Current longitude of delivery agent', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Ready for Pickup', 'Ready for Pickup'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Fulfilled', 'Fulfilled'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='VendorCategory',
        ),
    ]
