# Generated by Django 5.2 on 2025-05-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='fcm_token',
            field=models.CharField(blank=True, default=None, help_text='Device FCM token for notifications', max_length=256, null=True),
        ),
    ]
